config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/ski_shops', to: 'ski_shop#index'

  get '/ski_shops/new', to: 'ski_shop#new'
  post '/ski_shops', to: 'ski_shop#create'

  get '/ski_shops/:id', to: 'ski_shop#show'
  get '/ski_shops/:id/edit', to: 'ski_shop#edit'
  patch '/ski_shops/:id', to: 'ski_shop#update'
  get '/ski_shops/:id/skis', to: 'ski_shop_skis#index'

  get '/ski_shops/:id/skis/new', to: 'ski_shop_skis#new'
  post '/ski_shops/:id/skis', to: 'ski_shop_skis#create'

  get '/skis', to: 'skis#index'
  get '/skis/:id', to: 'skis#show'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ski.rb
class Ski < ApplicationRecord
  belongs_to :ski_shop

end

app/models/ski_shop.rb
class SkiShop < ApplicationRecord
  has_many :skis
  
  def self.shop_order
    SkiShop.order(created_at: :desc)
  end

  def ski_count
    skis.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ski_shop_controller.rb
class SkiShopController < ApplicationController
  def index
    @ski_shops = SkiShop.all.order(created_at: :desc)
  end

  def show
    @ski_shop = SkiShop.find(params[:id])
    @ski_count = @ski_shop.ski_count
  end

  def new
  end

  def create
    SkiShop.create!(ski_shop_params)
    redirect_to '/ski_shops'
  end

  def edit
    @ski_shop = SkiShop.find(params[:id])
  end

  def update
    @ski_shop = SkiShop.find(params[:id])
    @ski_shop.update(ski_shop_params)
    redirect_to "/ski_shops/#{@ski_shop.id}"
  end

  private
  def ski_shop_params
    params.permit(:name, :location_quantity, :rents_clothes)
  end
end

app/controllers/ski_shop_skis_controller.rb
class SkiShopSkisController < ApplicationController
  def index
    @ski_shop = SkiShop.find(params[:id])
    @skis = @ski_shop.skis
  end

  def new
    @ski_shop = SkiShop.find(params[:id])
  end
  
  def create
    ski_shop = SkiShop.find(params[:id])
    new_ski = Ski.create!(ski_params)

    new_ski.save

    redirect_to "/ski_shops/#{ski_shop.id}/skis"
  end
  private
  def ski_params
    params.permit(:year, :manufacturer, :model, :fleet, :length, :width, :needs_tuned, :ski_shop_id)
  end
end

app/controllers/skis_controller.rb
class SkisController < ApplicationController
  def index
    @skis = Ski.all
  end
  
  def show
    @ski = Ski.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkiShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= link_to "Skis", skis_path %> <%= link_to "Ski Shops", ski_shops_path %>
    <%= yield %>
  </body>
</html>

app/views/ski_shop/edit.html.erb
<h1>Edit Ski Shop Form</h1>

<%= form_with url: "/ski_shops/#{@ski_shop.id}", method: :patch, local: true do |form| %>
<%= form.label :name, "Name:" %>
<%= form.text_field :name, value: @ski_shop.name %>
<%= form.label :location_quantity, "Location Quantity:" %>
<%= form.text_field :location_quantity, value: @ski_shop.location_quantity %>
<%= form.label :rents_clothes, "Rents Clothes?:" %>
<%= form.text_field :rents_clothes, value: @ski_shop.rents_clothes %>

<%= form.submit "Submit"%>
<% end %>

app/views/ski_shop/index.html.erb
<h1>Ski Shops</h1>
<%= link_to 'New Ski Shop', '/ski_shops/new' %>
<% @ski_shops.each do |ski_shop| %>
<h2><%= ski_shop.name %> <%= ski_shop.created_at %></h2>
<% end %>

app/views/ski_shop/new.html.erb
<h1>New Ski Shop Form</h1>

<%= form_with url:'/ski_shops', method: :post, local: true do |form| %>
<%= form.label :name, "Name:" %>
<%= form.text_field :name %>
<%= form.label :location_quantity, "Location Quantity:" %>
<%= form.text_field :location_quantity %>
<%= form.label :rents_clothes, "Rents Clothes?:" %>
<%= form.text_field :rents_clothes %>

<%= form.submit "Create Ski Shop"%>
<% end %>

app/views/ski_shop/show.html.erb
<h1><%= @ski_shop.name %></h2>
<p>Number of Locations: <%= @ski_shop.location_quantity %></p>
<p>Rents Clothes?: <%= @ski_shop.rents_clothes %></p>
<p>Ski Count: <%= @ski_count %></p>
<p><%= link_to "Ski Shop Skis", "/ski_shops/#{@ski_shop.id}/skis" %></p>
<p><%= link_to "Update Ski Shop", "/ski_shops/#{@ski_shop.id}/edit", method: :get %></p>

app/views/ski_shop_skis/index.html.erb
<h1><%= @ski_shop.name %></h1>
<%= link_to "Create Ski", "/ski_shops/#{@ski_shop.id}/skis/new" %>
<% @skis.each do |ski| %>
  <h2><%= ski.year %> <%= ski.manufacturer %></h2>
  <p><%= ski.model %> <%= ski.fleet %></p>
  <p>Length (cm): <%= ski.length %></p>
  <p>Width (mm): <%= ski.width %></p>
  <p>Needs Tuned?: <%= ski.needs_tuned %></p>
  <p>Available at Ski Shop: <%= ski.ski_shop_id %></p>
<% end %>

app/views/ski_shop_skis/new.html.erb
<h1><%= "Create A New Ski for #{@ski_shop.name}" %></h1>

<%= form_with url: "/ski_shops/#{@ski_shop.id}/skis", method: :post, local: true do |form| %>
<%= form.label :year, "Year:" %>
<%= form.text_field :year %>
<%= form.label :manufacturer, "Manufacturer:" %>
<%= form.text_field :manufacturer %>
<%= form.label :model, "Model:" %>
<%= form.text_field :model %>
<%= form.label :fleet, "Fleet:" %>
<%= form.text_field :fleet %>
<%= form.label :length, "Ski Length:" %>
<%= form.text_field :length %>
<%= form.label :width, "Ski Width:" %>
<%= form.text_field :width %>
<%= form.label :needs_tuned, "Ski Needs Tuned?:" %>
<%= form.text_field :needs_tuned %>
<%= form.hidden_field :ski_shop_id, value: @ski_shop.id %>

<%= form.submit "Create Ski"%>
<% end %>

app/views/skis/index.html.erb
<h1>Skis Available<h1>

<% @skis.each do |ski| %>

  <h2><%= ski.year %> <%= ski.manufacturer %></h2>
  <p><%= ski.model %> <%= ski.fleet %></p>
  <p>Length (cm): <%= ski.length %></p>
  <p>Width (mm): <%= ski.width %></p>
  <p>Needs Tuned?: <%= ski.needs_tuned %></p>
  <p>Available at Ski Shop: <%= ski.ski_shop_id %></p>
<% end %>

app/views/skis/show.html.erb
<h1><%= @ski.year %> <%= @ski.manufacturer %></h1>
<p><%= @ski.model %> <%= @ski.fleet %></p>
<p>Length (cm): <%= @ski.length %></p>
<p>Width (mm): <%= @ski.width %></p>
<p>Needs Tuned?: <%= @ski.needs_tuned %></p>
<p>Available at Ski Shop: <%= @ski.ski_shop_id %></p>